### PR TITLE
Allow overriding group colors

### PR DESCRIPTION
**Pull request by tzachar**
For example, use the following lua config:
```lua
-- zephyr override
vim.g.zephyr = {
	override = {
		TSVariable = {fg='wheat'};
	};
}
```

### CODE REVIEW

**Comment by tzachar** [comment]
Anything on this PR?

**Comment by tzachar** [comment]
Is this project dead?

**Comment by glepnir** [comment]
alive

--------------原始邮件--------------
发件人："tzachar ***@***.***&gt;;
发送时间：2021年6月27日(星期天) 晚上8:01
收件人："glepnir/zephyr-nvim" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：Re: [glepnir/zephyr-nvim] Allow overriding group colors (#17)
-----------------------------------

 

 
Is this project dead?

**Comment by tzachar** [comment]
Anything on this PR?

**Comment by glepnir** [comment]
sorry I am in hospital when I go home I will check it

--------------原始邮件--------------
发件人："tzachar ***@***.***&gt;;
发送时间：2021年6月27日(星期天) 晚上8:05
收件人："glepnir/zephyr-nvim" ***@***.***&gt;;
抄送："Raphael ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [glepnir/zephyr-nvim] Allow overriding group colors (#17)
-----------------------------------

 

 
Anything on this PR?

**Comment by tzachar** [comment]
Sorry to hear that. Hope you get well soon :)

**Pull request merged**
